version: '3.0'

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    ports:
      - '4566:4566'


  aws-cli:
    image: mesosphere/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=sa-east-1

    entrypoint: /bin/sh -c

    command: >
      "
        sleep 5
        aws --endpoint-url=http://localstack:4566 sns create-topic --name order-topic
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name order-queue-created
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name order-queue-cancelled
        subscription_arn=$$(aws --endpoint-url=http://localstack:4566 sns subscribe --topic-arn arn:aws:sns:sa-east-1:000000000000:order-topic --protocol sqs --notification-endpoint arn:aws:sqs:sa-east-1:000000000000:order-queue-created --output text)
        echo $${subscription_arn}
        subscription_arn2=$$(aws --endpoint-url=http://localstack:4566 sns subscribe --topic-arn arn:aws:sns:sa-east-1:000000000000:order-topic --protocol sqs --notification-endpoint arn:aws:sqs:sa-east-1:000000000000:order-queue-cancelled --output text)
        echo $${subscription_arn2}
        aws --endpoint-url=http://localstack:4566 sns set-subscription-attributes --subscription-arn $${subscription_arn} --attribute-name FilterPolicy --attribute-value '{\"orderType\": [\"ORDER_CREATED\"]}'
        aws --endpoint-url=http://localstack:4566 sns set-subscription-attributes --subscription-arn $${subscription_arn} --attribute-name RawMessageDelivery --attribute-value true

        echo Concluído...
        echo Exibindo atributos da fila de created...
        aws --endpoint-url=http://localstack:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/order-queue-created --attribute-names All
        echo Exibindo atributos da fila de cancelled...
        aws --endpoint-url=http://localstack:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/order-queue-cancelled --attribute-names All
        echo Exibindo atributos do topico...
        aws --endpoint-url=http://localstack:4566 sns get-subscription-attributes --subscription-arn $${subscription_arn}
        echo Exibindo atributos do topico...
        aws --endpoint-url=http://localstack:4566 sns get-subscription-attributes --subscription-arn $${subscription_arn2}
        tail /dev/stdout
      "
    depends_on:
      - localstack