#localstack:
#  host: localhost

cloud:
  aws:
    credentials:
      access-key: foo
      secret-key: bar
    endpoint: http://localhost:4566
    sqs:
      order-queue-created:
        url: http://localhost:4566/000000000000/order-queue-created
        name: order-queue-created
      order-queue-cancelled:
        url: http://localhost:4566/000000000000/order-queue-cancelled
        name: order-queue-cancelled
    sns:
      order-topic:
        arn: arn:aws:sns:sa-east-1:000000000000:order-topic
        name: order-topic
    stack:
      auto: false
    region:
      static: sa-east-1
