#localstack:
#  host: localhost

cloud:
  aws:
    credentials:
      access-key: foo
      secret-key: bar
    endpoint: http://localhost:4566
    sqs:
      order-queue:
        url: http://localhost:4566/000000000000/order-queue
        name: order-queue
#      order-queue-2:
#        url: http://localhost:4566/000000000000/order-queue-2
#        name: order-queue-2
    sns:
      order-topic:
        arn: arn:aws:sns:eu-central-1:000000000000:order-topic
        name: order-topic
    stack:
      auto: false
    region:
      static: eu-central-1
